### ISSUE TITLE
Clarifying EDAM scope

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontologyDocs#18]
@matuskalas @hmenager @veitveit 

I’m doing a major spring-clean of EDAM docs, guidelines etc. trying to wrap up many things that have been lurking on threads, spreadsheets, from hackathons etc, well, for years now in some cases - this is needed for impending milestone & deliverable reports.

First thing is a re-definition of the scope of EDAM, which was:
_As a general rule, the Data, Format and Operation branches include concepts strictly in domain of bioinformatics and computational biology: concepts purely concerning biology, computer science etc. are not included. The Topic branch, in contrast, includes broader interdisciplinary concepts from the biological and biomedical domains._

And soon to be:
_As a general rule, the **Data**, **Format** and **Operation** branches include concepts strictly in the domain of informatics in the Life Sciences; primarily bioinformatics (broadly) and computational biology concepts useful for annotating software tools.  Concepts purely concerning biology, computer science *etc.* are not included. The **Topic** branch, in contrast, includes broader interdisciplinary concepts from the biological and biomedical domains._

Are you happy?
- [x] Jon
- [ ] Matus
- [ ] Herve
- [x] Veit

If not, let's hear it ... :)

**Comment by veitveit** [comment]
Looks good and thanks for the extensive work lately!

**Comment by joncison** [comment]
@matuskalas and @hmenager - I'm taking the radio silence of tacit approval, and closing this (you can always re-open)
