### ISSUE TITLE
Check colours of figures are the "formal" ones

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontologyDocs#19]
*i.e.* colours in figures here:
http://edamontologydocs.readthedocs.io/en/latest/what_is_edam.html

according to the scheme here:
https://github.com/edamontology/edamontology/issues/340

**Comment by matuskalas** [comment]
https://github.com/edamontology/edamontology/blob/7314e7e00f7c0208d254147b655676fe63de65b8/EDAMrelations.png
![image](https://raw.githubusercontent.com/edamontology/edamontology/7314e7e00f7c0208d254147b655676fe63de65b8/EDAMrelations.png)

https://github.com/edamontology/edamontology.org/blob/c3d0e8f6b1c1bb21ffa132f5d21e643bbc62ab31/EDAMconcepts.png
![image](https://raw.githubusercontent.com/edamontology/edamontology.org/c3d0e8f6b1c1bb21ffa132f5d21e643bbc62ab31/EDAMconcepts.png)

**Comment by matuskalas** [comment]
https://github.com/edamontology/edamontology/blob/7314e7e00f7c0208d254147b655676fe63de65b8/EDAMrelations.png
![image](https://raw.githubusercontent.com/edamontology/edamontology/7314e7e00f7c0208d254147b655676fe63de65b8/EDAMrelations.png)

https://github.com/edamontology/edamontology.org/blob/c3d0e8f6b1c1bb21ffa132f5d21e643bbc62ab31/EDAMconcepts.png
![image](https://raw.githubusercontent.com/edamontology/edamontology.org/c3d0e8f6b1c1bb21ffa132f5d21e643bbc62ab31/EDAMconcepts.png)

**For clarification, please see my https://github.com/edamontology/edamontology/issues/340#issuecomment-409548685.**
