### ISSUE TITLE
Explore EDAM Q&A forum

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontologyDocs#2]
e.g. BioStars, StackExchange

- how to follow specific "EDAM" tag / email alerting on new posts
- can we create short cut to create new EDAM post, e.g. "ask an EDAM question" button for use on EDAM docs etc.

cc @hmenager @matuskalas @veitveit

**Comment by matuskalas** [comment]
Oh, now we have twice the same issue :-) Please refer to #5 for further comments/info/follow-up
